#!/usr/bin/env python3
"""Create and index a Vertex AI Serverless RAG Corpus for EventOps AI.

Usage:
    python scripts/create_rag_corpus.py [--project PROJECT] [--location LOCATION] [--bucket BUCKET]
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

from google.cloud import storage
import vertexai
from vertexai.preview import rag
from vertexai.preview.rag.utils import resources as rr


def setup_rag(project_id: str, location: str, bucket_name: str, playbook_path: Path):
    if not playbook_path.exists():
        print(f"Error: Playbook file not found at {playbook_path}")
        sys.exit(1)

    print(f"1. Uploading {playbook_path} to gs://{bucket_name}/rag/{playbook_path.name}...")
    storage_client = storage.Client(project=project_id)
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(f"rag/{playbook_path.name}")
    blob.upload_from_filename(str(playbook_path), content_type="text/plain")
    gcs_dest = f"gs://{bucket_name}/rag/{playbook_path.name}"
    print(f"Uploaded playbook to {gcs_dest} successfully.")

    print(f"2. Initializing Vertex AI in {project_id} ({location})...")
    vertexai.init(project=project_id, location=location)

    cfg_name = f"projects/{project_id}/locations/{location}/ragEngineConfig"
    try:
        rag.update_rag_engine_config(
            rag_engine_config=rag.RagEngineConfig(
                name=cfg_name,
                rag_managed_db_config=rag.RagManagedDbConfig(mode=rr.Serverless()),
            )
        )
        print("Serverless RAG DB mode confirmed.")
    except Exception as e:
        print(f"Note on RAG engine config: {e}")

    # Check for existing corpus with display name
    corpus_display_name = "eventops-operations-playbook"
    corpora = list(rag.list_corpora())
    corpus = next((c for c in corpora if c.display_name == corpus_display_name), None)

    if corpus is None:
        print(f"3. Creating new serverless RAG corpus: '{corpus_display_name}'...")
        corpus = rag.create_corpus(
            display_name=corpus_display_name,
            embedding_model_config=rag.EmbeddingModelConfig(
                publisher_model="publishers/google/models/text-embedding-005"
            ),
        )
        print(f"Corpus created: {corpus.name}")
    else:
        print(f"3. Reusing existing corpus: {corpus.name}")

    print("4. Importing and indexing playbook using Gemini 2.5 Flash LLM parser...")
    resp = rag.import_files(
        corpus_name=corpus.name,
        paths=[gcs_dest],
        transformation_config=rag.TransformationConfig(
            chunking_config=rag.ChunkingConfig(chunk_size=512, chunk_overlap=100)
        ),
        llm_parser=rag.LlmParserConfig(
            model_name="gemini-2.5-flash",
            custom_parsing_prompt=(
                "Extract the practical operational benchmarks, timing rules, accessibility guidelines, "
                "budget rules, and event coordination standards described in this text. "
                "Ignore and omit all metadata. Output clean, self-contained prose."
            ),
        ),
    )
    print(f"Import complete! Imported files count: {resp.imported_rag_files_count}")

    # Save to app/rag_config.py
    config_path = Path(__file__).resolve().parent.parent / "app" / "rag_config.py"
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(f'# Generated by create_rag_corpus.py\nCORPUS_NAME = "{corpus.name}"\n')
    print(f"Saved active CORPUS_NAME to {config_path}")
    return corpus.name


def main():
    parser = argparse.ArgumentParser(description="Bootstrap Vertex AI RAG Corpus for EventOps AI")
    parser.add_argument(
        "--project",
        default=os.environ.get("GOOGLE_CLOUD_PROJECT", "qwiklabs-gcp-04-a69f0245a9b4"),
        help="GCP Project ID",
    )
    parser.add_argument(
        "--location",
        default=os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1"),
        help="Vertex AI region (default: us-central1)",
    )
    parser.add_argument(
        "--bucket",
        default=os.environ.get(
            "EVENTOPS_MEDIA_BUCKET",
            f"eventops-ai-media-{os.environ.get('GOOGLE_CLOUD_PROJECT', 'qwiklabs-gcp-04-a69f0245a9b4')}",
        ),
        help="GCS Bucket for storing playbook document",
    )
    parser.add_argument(
        "--playbook",
        default="knowledge/event_operations_playbook.txt",
        help="Path to operations playbook text file",
    )

    args = parser.parse_args()
    playbook_path = Path(args.playbook)
    if not playbook_path.exists():
        playbook_path = Path("docs/event_operations_playbook.txt")

    setup_rag(args.project, args.location, args.bucket, playbook_path)


if __name__ == "__main__":
    main()
