# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Set up serverless Vertex AI RAG corpus for EventOps AI operations playbook."""

from pathlib import Path
import time

from google.cloud import storage
import vertexai
from vertexai.preview import rag
from vertexai.preview.rag.utils import resources as rr

PROJECT_ID = "qwiklabs-gcp-04-a69f0245a9b4"
LOCATION = "us-central1"
BUCKET_NAME = "eventops-ai-media-qwiklabs-gcp-04-a69f0245a9b4"
PLAYBOOK_FILE = Path(__file__).resolve().parent.parent / "docs" / "event_operations_playbook.txt"
GCS_DEST = f"gs://{BUCKET_NAME}/rag/event_operations_playbook.txt"


def setup_rag():
    print(f"1. Uploading {PLAYBOOK_FILE} to {GCS_DEST}...")
    storage_client = storage.Client(project=PROJECT_ID)
    bucket = storage_client.bucket(BUCKET_NAME)
    blob = bucket.blob("rag/event_operations_playbook.txt")
    blob.upload_from_filename(str(PLAYBOOK_FILE), content_type="text/plain")
    print("Uploaded playbook to Cloud Storage successfully.")

    print("2. Initializing Vertex AI and serverless RAG Engine...")
    vertexai.init(project=PROJECT_ID, location=LOCATION)

    cfg_name = f"projects/{PROJECT_ID}/locations/{LOCATION}/ragEngineConfig"
    try:
        rag.update_rag_engine_config(
            rag_engine_config=rag.RagEngineConfig(
                name=cfg_name,
                rag_managed_db_config=rag.RagManagedDbConfig(mode=rr.Serverless()),
            )
        )
        print("Serverless mode confirmed.")
    except Exception as e:
        print(f"RAG engine config status: {e}")

    # Check existing corpora
    corpora = list(rag.list_corpora())
    corpus = None
    for c in corpora:
        if c.display_name == "eventops-operations-playbook":
            corpus = c
            print(f"Found existing corpus: {corpus.name}")
            break

    if corpus is None:
        print("3. Creating new serverless RAG corpus: eventops-operations-playbook...")
        corpus = rag.create_corpus(
            display_name="eventops-operations-playbook",
            embedding_model_config=rag.EmbeddingModelConfig(
                publisher_model="publishers/google/models/text-embedding-005"
            ),
        )
        print(f"Corpus created: {corpus.name}")

    print("4. Importing and indexing playbook with Gemini LLM parser...")
    resp = rag.import_files(
        corpus_name=corpus.name,
        paths=[GCS_DEST],
        transformation_config=rag.TransformationConfig(
            chunking_config=rag.ChunkingConfig(chunk_size=512, chunk_overlap=100)
        ),
        llm_parser=rag.LlmParserConfig(
            model_name="gemini-2.5-flash",
            custom_parsing_prompt=(
                "Extract the practical operational benchmarks, timing rules, accessibility guidelines, "
                "budget rules, and event coordination standards described in this text. "
                "Ignore and omit all metadata. Output clean, self-contained prose."
            ),
        ),
    )
    print(f"Import complete! Imported files: {resp.imported_rag_files_count}")

    # Save corpus name to config file
    config_path = Path(__file__).resolve().parent.parent / "app" / "rag_config.py"
    with open(config_path, "w") as f:
        f.write(f'# Generated by setup_rag_playbook.py\nCORPUS_NAME = "{corpus.name}"\n')
    print(f"Saved CORPUS_NAME to {config_path}")

    return corpus.name


if __name__ == "__main__":
    setup_rag()
